// Code generated by mockery v1.0.0. DO NOT EDIT.

package request

import mock "github.com/stretchr/testify/mock"
import spec "github.com/go-openapi/spec"

// MockSchemaValidator is an autogenerated mock type for the SchemaValidator type
type MockSchemaValidator struct {
	mock.Mock
}

// SchemaValidator provides a mock function with given fields:
func (_m *MockSchemaValidator) SchemaValidator() *spec.Schema {
	ret := _m.Called()

	var r0 *spec.Schema
	if rf, ok := ret.Get(0).(func() *spec.Schema); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*spec.Schema)
		}
	}

	return r0
}
