// Code generated by mockery v1.0.0. DO NOT EDIT.

package encoder

import http "net/http"
import mock "github.com/stretchr/testify/mock"

// MockEncoder is an autogenerated mock type for the Encoder type
type MockEncoder struct {
	mock.Mock
}

// Encode provides a mock function with given fields: w, data
func (_m *MockEncoder) Encode(w http.ResponseWriter, data interface{}) error {
	ret := _m.Called(w, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(http.ResponseWriter, interface{}) error); ok {
		r0 = rf(w, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MimeType provides a mock function with given fields:
func (_m *MockEncoder) MimeType() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
